TestConfig:
  Name: B0-random-DM3
  Experiments: 1
  Iterations: 100
  WaitDuration: 10 # Time duration to wait between execution steps in milliseconds
  StartupDuration: 6 #so msg Q is not empty
SchedulerConfig:
  Type: "random" 
  Steps: 400
  Seed: 16
  Params:  {"fault_probability": 0.05} 
  ClientRequests: 0
  FaultQuota: 3
NetworkConfig:
  BaseReplicaPort: 8100
  BaseInterceptorPort: 10000
  Protocol: "http" # brpc uses http2
  MessageType: GRPC
FaultConfig:
  Faults: 
ProcessConfig:
  NumReplicas: 3
  Timeout: 30
  OutputDir: output
  ReplicaScript: scripts/braft_server_relative.sh
  ClientScripts: [] # 
  CleanScript: scripts/braft_clean.sh
  ReplicaParams:
    - "8100 10001 10002 0 8100"
    - "10003 8101 10005 1 8101"
    - "10006 10007 8102 2 8102"
