TestConfig:
  Name: test
  Experiments: 1
  Iterations: 100
  WaitDuration: 10 # Time duration to wait between execution steps in milliseconds
  StartupDuration: 6 #so msg Q is not emptyh
  RecoveryPoint: 30
SchedulerConfig:
  Type: "random" 
  Steps: 40
  Seed: 16
  Params: {"client_request_probability": 0.5, "d": 1,"fault_probability": 0.05} 
  ClientRequests: 0
  FaultQuota: 4
NetworkConfig:
  BaseReplicaPort: 8100
  BaseInterceptorPort: 10000
  Protocol: "http" # brpc uses http2
  MessageType: GRPC
FaultConfig:
  Faults: 
      Type: dropmessage
      Params:
ProcessConfig:
  NumReplicas: 3
  Timeout: 20
  OutputDir: output
  ReplicaScript: scripts/braft_server_relative.sh
  ClientScripts: [ scripts/braft_client1.sh ] # 
  CleanScript: scripts/braft_clean.sh
  ReplicaParams:
    - "8100 10001 10002 0 8100"
    - "10003 8101 10005 1 8101"
    - "10006 10007 8102 2 8102"
